//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.MapsSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_maps_limit
    {
        public int map_limit_id { get; set; }
        public Nullable<int> map_id { get; set; }
        public Nullable<int> limit_zoom { get; set; }
        public Nullable<int> limit_x_min { get; set; }
        public Nullable<int> limit_x_max { get; set; }
        public Nullable<int> limit_y_min { get; set; }
        public Nullable<int> limit_y_max { get; set; }
    }
}
