//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.MapsSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_schedule_versions
    {
        public int version_id { get; set; }
        public string version_name { get; set; }
        public Nullable<System.DateTime> version_preview_date { get; set; }
        public Nullable<System.DateTime> version_start_date { get; set; }
        public string version_update_by { get; set; }
        public Nullable<int> version_update_in_progress { get; set; }
        public Nullable<System.DateTime> version_update_timestamp { get; set; }
        public Nullable<int> is_processing { get; set; }
    }
}
