//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.MapsSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_timepoints
    {
        public int timepoint_id { get; set; }
        public Nullable<int> schedule_id { get; set; }
        public string timepoint_code { get; set; }
        public string timepoint_name { get; set; }
        public string city { get; set; }
        public Nullable<int> city_redundancy { get; set; }
        public string neighborhood { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string timepoint_notes { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
