//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.MapsSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_day_codes
    {
        public string day_code { get; set; }
        public string adjectives { get; set; }
        public string long_names { get; set; }
        public string longer_names { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
