//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.MapsSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_alerts
    {
        public int alert_id { get; set; }
        public Nullable<System.DateTime> alert_date { get; set; }
        public Nullable<System.DateTime> alert_start_date { get; set; }
        public Nullable<System.DateTime> alert_end_date { get; set; }
        public string alert_name { get; set; }
        public string alert_description { get; set; }
        public Nullable<int> alert_is_draft { get; set; }
    }
}
