//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.MapsSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_schedule
    {
        public int schedule_id { get; set; }
        public string schedule_code { get; set; }
        public Nullable<int> schedule_type { get; set; }
        public Nullable<int> line_group_id { get; set; }
        public string type { get; set; }
        public string notes { get; set; }
        public Nullable<int> schedule_id_equivalent { get; set; }
        public string direction_code { get; set; }
        public string day_code { get; set; }
    }
}
