//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.MapsSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_alert_lines
    {
        public int recid { get; set; }
        public Nullable<int> alert_id { get; set; }
        public Nullable<int> line_id { get; set; }
    }
}
