//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.MapsSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_maps
    {
        public int map_id { get; set; }
        public Nullable<int> version_id { get; set; }
        public string map_code { get; set; }
        public Nullable<int> map_category_id { get; set; }
        public string map_city { get; set; }
        public Nullable<int> map_type { get; set; }
        public string map_center_lat_lng_zoom { get; set; }
    }
}
