//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Transportation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string booking_id { get; set; }
        public short booking_num { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string description { get; set; }
        public int creation_sequence { get; set; }
        public int default_special_trip_option_id { get; set; }
        public long BookingId { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public System.DateTime UpdDateTime { get; set; }
        public string SignupPeriodNum { get; set; }
        public string SignupPeriodDesc { get; set; }
        public string StatusNameDesc { get; set; }
    }
}
