//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Transportation
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInterface
    {
        public int EmployeeInterfaceId { get; set; }
        public string Role { get; set; }
        public bool IsEnabled { get; set; }
        public string JobTitle { get; set; }
        public string DeptName { get; set; }
        public string Location { get; set; }
        public string DefaultStatusCode { get; set; }
    }
}
