//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Transportation
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident_log
    {
        public int incident_log_id { get; set; }
        public int trip_id { get; set; }
        public System.DateTime incident_date_time { get; set; }
        public System.DateTime transit_date_time { get; set; }
        public short incident_code { get; set; }
        public short incident_type { get; set; }
        public byte incident_status { get; set; }
        public int vehicle_id { get; set; }
        public int driver_id { get; set; }
        public int block_id { get; set; }
        public int route_id { get; set; }
        public int run_id { get; set; }
        public int dispatcher_id { get; set; }
        public byte open_ir { get; set; }
        public short deviation { get; set; }
        public int tp_id { get; set; }
        public int next_tp_id { get; set; }
        public System.DateTime last_incident_date_time { get; set; }
        public System.DateTime sched_time { get; set; }
        public byte direction_code_id { get; set; }
        public byte division_id { get; set; }
        public byte sched_version { get; set; }
        public int user_handled { get; set; }
        public System.DateTime handled_datetime { get; set; }
        public string incident_details { get; set; }
        public int incident_owner { get; set; }
        public int current_route_id { get; set; }
    }
}
