//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Transportation
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRealTime
    {
        public int VehicleId { get; set; }
        public int VehiclePositionLogId { get; set; }
        public int IncidentLogId { get; set; }
        public Nullable<System.DateTime> VehiclePositionDateTime { get; set; }
        public Nullable<double> VehicleLongitude { get; set; }
        public Nullable<double> VehicleLatitude { get; set; }
        public Nullable<short> VehicleHeading { get; set; }
        public Nullable<byte> VehicleAverageSpeed { get; set; }
        public Nullable<short> VehiclePredictedDeviation { get; set; }
        public Nullable<System.DateTime> VehiclePlaybackDateTime { get; set; }
        public string VehicleLicenseNumber { get; set; }
        public string VehicleIdentificationNumber { get; set; }
        public byte VehicleMakeId { get; set; }
        public short VehicleModelYear { get; set; }
        public byte VehicleType { get; set; }
        public bool VehicleWheelchairAccessible { get; set; }
        public short VehiclePassengerCapacity { get; set; }
        public string Division { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public System.DateTime TransitDateTime { get; set; }
        public short IncidentCode { get; set; }
        public string IncidentCodeDesc { get; set; }
        public short IncidentType { get; set; }
        public string IncidentTypeDesc { get; set; }
        public byte IncidentStatus { get; set; }
        public System.DateTime IncidentSchedTime { get; set; }
        public int RouteId { get; set; }
        public byte SchedVersion { get; set; }
        public string BookingNum { get; set; }
        public string booking_id { get; set; }
        public string DayTypeId { get; set; }
        public int CurrentRouteId { get; set; }
        public string CurrentRouteAlpha { get; set; }
        public int BlockId { get; set; }
        public string BlockName { get; set; }
        public int RunId { get; set; }
        public string TripId { get; set; }
        public int TripDistance { get; set; }
        public System.DateTime TripStartTime { get; set; }
        public int TripStartLayover { get; set; }
        public System.DateTime TripEndTime { get; set; }
        public int TripEndLayover { get; set; }
        public string TripVariation { get; set; }
        public string TripTypeDesc { get; set; }
        public int TimepointId { get; set; }
        public int NextTimepointId { get; set; }
        public int DriverId { get; set; }
        public byte DirectionCodeId { get; set; }
        public short Deviation { get; set; }
        public System.DateTime IncidentPlaybackTime { get; set; }
    }
}
