//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.DataAccess.MapsSchedules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ACTransit.Entities.MapsSchedules;
    public partial class MapsEntities : DbContext
    {
        public MapsEntities()
            : base("name=MapsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<sch_day_codes> sch_day_codes { get; set; }
        public virtual DbSet<sch_direction_codes> sch_direction_codes { get; set; }
        public virtual DbSet<sch_footnote> sch_footnote { get; set; }
        public virtual DbSet<sch_lines> sch_lines { get; set; }
        public virtual DbSet<sch_maps> sch_maps { get; set; }
        public virtual DbSet<sch_maps_limit> sch_maps_limit { get; set; }
        public virtual DbSet<sch_schedule> sch_schedule { get; set; }
        public virtual DbSet<sch_schedule_lines> sch_schedule_lines { get; set; }
        public virtual DbSet<sch_special_day_codes> sch_special_day_codes { get; set; }
        public virtual DbSet<sch_timepoints> sch_timepoints { get; set; }
        public virtual DbSet<sch_trips> sch_trips { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<sch_alert_lines> sch_alert_lines { get; set; }
        public virtual DbSet<sch_alerts> sch_alerts { get; set; }
        public virtual DbSet<sch_schedule_versions> sch_schedule_versions { get; set; }
        public virtual DbSet<sch_schedule_line_name_info> sch_schedule_line_name_info { get; set; }
        public virtual DbSet<sch_schedule_line_search> sch_schedule_line_search { get; set; }
    }
}
