//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesLocation
    {
        public long EmployeesLocationId { get; set; }
        public string Badge { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime BeginEffDate { get; set; }
        public System.DateTime EndEffDate { get; set; }
        public string Empl_Status { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Location { get; set; }
        public string Per_Org { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public System.DateTime UpdDateTime { get; set; }
    }
}
