//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_Id { get; set; }
        public string Badge { get; set; }
        public System.DateTime ETLDateTime { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public string Pref_Name { get; set; }
        public string NTLogin { get; set; }
        public Nullable<System.DateTime> Hire_Dt { get; set; }
        public Nullable<System.TimeSpan> HireTime { get; set; }
        public Nullable<System.DateTime> Rehire_Dt { get; set; }
        public Nullable<System.DateTime> BusDriverQualDate { get; set; }
        public Nullable<System.TimeSpan> BusDriverQualTime { get; set; }
        public Nullable<System.DateTime> LastWorkDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address01 { get; set; }
        public string Address02 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string PreferredPhone { get; set; }
        public string WorkPhone { get; set; }
        public string CellPhone { get; set; }
        public string EmailAddress { get; set; }
        public string Empl_Status { get; set; }
        public string DeptId { get; set; }
        public string DeptName { get; set; }
        public string Location { get; set; }
        public string Company { get; set; }
        public string JobCode { get; set; }
        public string PayGroup { get; set; }
        public string JobTitle { get; set; }
        public string BusinessTitle { get; set; }
        public string Empl_Type { get; set; }
        public string RegTempFlag { get; set; }
        public string FT_PT_Flag { get; set; }
        public string Per_Org { get; set; }
        public string SupervisorId { get; set; }
        public string SupervisorName { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string ActionReason { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public string UnionCode { get; set; }
        public string EEO4Code { get; set; }
        public string EEOJobGroup { get; set; }
        public string CompFrequency { get; set; }
        public Nullable<decimal> CompRate { get; set; }
        public Nullable<decimal> AnnualRate { get; set; }
        public Nullable<decimal> MonthlyRate { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public string Grade { get; set; }
        public string Step { get; set; }
        public string PositionNumber { get; set; }
        public Nullable<System.DateTime> PositionEntryDate { get; set; }
        public string Sex { get; set; }
        public string EthnicGroup { get; set; }
        public string Veteran { get; set; }
        public string Citizen { get; set; }
        public string Disabled { get; set; }
        public string Marital { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<decimal> VacHoursEntitlement { get; set; }
        public Nullable<decimal> VacHoursCarryover { get; set; }
        public string DriverLicenseNumber { get; set; }
        public Nullable<System.DateTime> DriverLicenseExpirationDate { get; set; }
        public Nullable<System.DateTime> MedicalExpirationDate { get; set; }
        public Nullable<System.DateTime> StepStartDate { get; set; }
        public string WorkShift { get; set; }
        public string ScheduledDaysOff { get; set; }
        public string PSBadge { get; set; }
        public string AddUserId { get; set; }
        public Nullable<System.DateTime> AddDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string SecurityCardFormatted { get; set; }
        public string SecurityCardNumber { get; set; }
        public Nullable<bool> SecurityCardEnabled { get; set; }
        public Nullable<decimal> SecurityCardEncoded { get; set; }
        public Nullable<System.DateTime> SecurityETLDateTime { get; set; }
    }
}
