//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAll
    {
        public string Badge { get; set; }
        public string EmployeeName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Location { get; set; }
        public string Division { get; set; }
        public string Per_Org { get; set; }
        public string Suffix { get; set; }
        public string NTLogin { get; set; }
        public string Empl_Status { get; set; }
        public string DeptName { get; set; }
        public System.DateTime BeginEffDate { get; set; }
        public System.DateTime EndEffDate { get; set; }
        public long EmployeesLocationId { get; set; }
        public int InEmpTable { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> StepStartDate { get; set; }
        public string WorkShift { get; set; }
        public string ScheduledDaysOff { get; set; }
        public string PSBadge { get; set; }
    }
}
