//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class VContacts_list
    {
        public string Badge { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string Department { get; set; }
        public string BusinessPhone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string DeptId { get; set; }
        public string Location { get; set; }
        public string JobTitle { get; set; }
        public string SupervisorName { get; set; }
        public string Pref_Name { get; set; }
    }
}
