//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.CustomerRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachmentsTemp
    {
        public int Id { get; set; }
        public int AttachmentNum { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string ContentType { get; set; }
        public string Base64Data { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public Nullable<System.DateTime> DateScanStart { get; set; }
        public string ScanId { get; set; }
        public string Sha256 { get; set; }
        public string ScanResult { get; set; }
        public int FileNum { get; set; }
        public Nullable<bool> ForceClose { get; set; }
    
        public virtual tblContacts tblContacts { get; set; }
    }
}
