//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.CustomerRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachments
    {
        public int FileNum { get; set; }
        public int AttachmentNum { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string ContentType { get; set; }
        public byte[] BinaryData { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public string UploadedBy { get; set; }
        public string Description { get; set; }
    
        public virtual tblContacts tblContacts { get; set; }
    }
}
