//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.CustomerRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerComplaintCodes
    {
        public string ComplaintCode { get; set; }
        public string ComplaintGroup { get; set; }
        public string ComplaintCategory { get; set; }
        public string Description { get; set; }
        public Nullable<int> PastDueDays { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    }
}
