//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.CustomerRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIncidentUpdateHistory
    {
        public int FileNum { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> LastIncidentDateTime { get; set; }
        public string LastVehNo { get; set; }
        public string LastRoute { get; set; }
        public string LastBadge { get; set; }
        public Nullable<System.DateTime> NewIncidentDateTime { get; set; }
        public string NewVehNo { get; set; }
        public string NewRoute { get; set; }
        public string NewBadge { get; set; }
        public int Id { get; set; }
    
        public virtual tblContacts tblContacts { get; set; }
    }
}
