//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.CustomerRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLinkedContacts
    {
        public int Id { get; set; }
        public int FileNum { get; set; }
        public int LinkedFileNum { get; set; }
        public bool Active { get; set; }
    
        public virtual tblContacts tblContacts { get; set; }
        public virtual tblContacts tblContacts1 { get; set; }
    }
}
