//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.CustomerRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUpdateLog
    {
        public string UserId { get; set; }
        public int FileNum { get; set; }
        public string TableName { get; set; }
        public string UpdateAction { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int Id { get; set; }
        public string ColumnName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual tblContacts tblContacts { get; set; }
    }
}
