//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.CustomerRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViewHistory
    {
        public int ViewHistoryId { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateFirstView { get; set; }
        public System.DateTime DateLastView { get; set; }
    
        public virtual tblContacts tblContacts { get; set; }
    }
}
