//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling.Gtfs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportLog
    {
        public int ImportLogId { get; set; }
        public int ImportInfoId { get; set; }
        public int ImportStepId { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Description { get; set; }
        public bool Successful { get; set; }
        public string ErrorText { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual ImportInfo ImportInfo { get; set; }
        public virtual ImportStep ImportStep { get; set; }
    }
}
