//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling.Gtfs
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopTime
    {
        public string BookingId { get; set; }
        public string TripId { get; set; }
        public string StopId { get; set; }
        public string ArrivalTime { get; set; }
        public string DepartureTime { get; set; }
        public int Sequence { get; set; }
        public string PickupType { get; set; }
        public string DropOffType { get; set; }
        public string StopHeadsign { get; set; }
        public Nullable<decimal> DistanceTraveled { get; set; }
        public Nullable<bool> Timepoint { get; set; }
    
        public virtual Stop Stop { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
