//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling.Gtfs
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripMap
    {
        public string BookingId { get; set; }
        public int TripId { get; set; }
        public string GtfsTripId { get; set; }
    
        public virtual Trip Trip { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
