//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public string BookingId { get; set; }
        public string ScheduleType { get; set; }
        public string Garage { get; set; }
        public int BlockNumber { get; set; }
        public string AllRoutes { get; set; }
        public byte RouteCount { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime StartPrdTime { get; set; }
        public string PlaceIdStartNoPull { get; set; }
        public string PlaceIdEndNoPull { get; set; }
        public System.DateTime EndPrdTime { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public short Duration { get; set; }
        public short InServiceDuration { get; set; }
        public short Layover { get; set; }
        public decimal Distance { get; set; }
        public decimal DistanceInService { get; set; }
        public short TripCountInService { get; set; }
        public short TripCount { get; set; }
        public bool OperatesSunday { get; set; }
        public bool OperatesMonday { get; set; }
        public bool OperatesTuesday { get; set; }
        public bool OperatesWednesday { get; set; }
        public bool OperatesThursday { get; set; }
        public bool OperatesFriday { get; set; }
        public bool OperatesSaturday { get; set; }
        public bool HasOpException { get; set; }
        public string StatusCode { get; set; }
        public string EvtStatDsp { get; set; }
        public string VehicleGroup { get; set; }
        public string VehicleType { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public System.DateTime UpdDateTime { get; set; }
        public long SysRecNo { get; set; }
        public string BlockCode { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
