//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Places = new HashSet<Place>();
        }
    
        public int DistrictId { get; set; }
        public string DistrictDescription { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public System.DateTime UpdDateTime { get; set; }
        public long SysRecNo { get; set; }
    
        public virtual ICollection<Place> Places { get; set; }
    }
}
