//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.TripTimingPoints = new HashSet<TripTimingPoint>();
            this.TripTimingPoints1 = new HashSet<TripTimingPoint>();
            this.TripTimingPoints2 = new HashSet<TripTimingPoint>();
            this.Stops = new HashSet<Stop>();
        }
    
        public string PlaceId { get; set; }
        public string PlaceReferenceId { get; set; }
        public string PlaceShortDescription { get; set; }
        public string PlaceDescription { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public System.DateTime UpdDateTime { get; set; }
        public long SysRecNo { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<TripTimingPoint> TripTimingPoints { get; set; }
        public virtual ICollection<TripTimingPoint> TripTimingPoints1 { get; set; }
        public virtual ICollection<TripTimingPoint> TripTimingPoints2 { get; set; }
        public virtual ICollection<Stop> Stops { get; set; }
    }
}
