//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopDistrict
    {
        public string StopId { get; set; }
        public int Id511 { get; set; }
        public string district { get; set; }
        public string StopDescription { get; set; }
        public string PlaceId { get; set; }
        public bool IsPublic { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public bool AllowAlighting { get; set; }
        public bool AllowBoarding { get; set; }
        public string Corner { get; set; }
        public bool IsBart { get; set; }
        public bool IsTransitCenter { get; set; }
        public bool IsInService { get; set; }
        public System.DateTime UpdDateTime { get; set; }
        public string UpdUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string AddUserId { get; set; }
        public string FlagRoute { get; set; }
        public System.DateTime LastSchedulerUpdate { get; set; }
        public string Comment { get; set; }
        public string AvaDescription { get; set; }
        public bool AvaStatus { get; set; }
        public string Site { get; set; }
        public bool IsGPSValidated { get; set; }
    }
}
