//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripStop
    {
        public int TripNumber { get; set; }
        public short PositionNumber { get; set; }
        public string PlaceId { get; set; }
        public decimal Distance { get; set; }
        public System.DateTime PassingTime { get; set; }
        public string StopId { get; set; }
        public int Id511 { get; set; }
        public bool IsLast { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
        public string AddUserID { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserID { get; set; }
        public System.DateTime UpdDateTime { get; set; }
    
        public virtual Stop Stop { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
