//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripTimingPoint
    {
        public int TripNumber { get; set; }
        public short PositionNumber { get; set; }
        public string TripTimingPointPlaceId { get; set; }
        public System.DateTime PassingTime { get; set; }
        public decimal Distance { get; set; }
        public bool IsArrival { get; set; }
        public bool IsDeparture { get; set; }
        public bool IsExported { get; set; }
        public bool IsPublic { get; set; }
        public bool IsLast { get; set; }
        public string PreviousPlaceId { get; set; }
        public Nullable<System.DateTime> PassingTimePrevious { get; set; }
        public string NextPlaceId { get; set; }
        public Nullable<System.DateTime> PassingTimeNext { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
        public string AddUserID { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserID { get; set; }
        public System.DateTime UpdDateTime { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Place Place1 { get; set; }
        public virtual Place Place2 { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
