//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Scheduling
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripPattern
    {
        public TripPattern()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public string RouteAlpha { get; set; }
        public short PatternId { get; set; }
        public string VariantId { get; set; }
        public string Direction { get; set; }
        public bool InService { get; set; }
        public string FirstTp { get; set; }
        public string LastTp { get; set; }
        public decimal Distance { get; set; }
        public Nullable<short> VehicleDisplayCode { get; set; }
        public string DrivingInstructions { get; set; }
        public System.DateTime AssignDate { get; set; }
        public short TripsMatch { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
        public string AddUserID { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserID { get; set; }
        public System.DateTime UpdDateTime { get; set; }
        public long SysRecNo { get; set; }
        public string BookingID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual RouteList RouteList { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
