//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.DataAccess.Scheduling.Gtfs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ACTransit.Entities.Scheduling.Gtfs;
    
    public partial class SchedulingGtfsEntities : DbContext
    {
        public SchedulingGtfsEntities()
            : base("name=SchedulingGtfsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<CalendarDate> CalendarDates { get; set; }
        public virtual DbSet<ImportInfo> ImportInfoes { get; set; }
        public virtual DbSet<ImportLog> ImportLogs { get; set; }
        public virtual DbSet<ImportStep> ImportSteps { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Shape> Shapes { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<StopTime> StopTimes { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripMap> TripMaps { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
    }
}
